version: '3.8'
services:
    db:
        image: mongo:latest
        container_name: mongo-container
        ports:
            - 27017:27017
        volumes:
            - mongo_db:/data/db

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ''
            ME_CONFIG_MONGODB_ADMINPASSWORD: ''
            ME_CONFIG_MONGODB_SERVER: db
            ME_CONFIG_BASICAUTH: false

    backend:
        build: ./backend       
        image: backend-app
        container_name: backend-container
        ports:
            - 5000:5000
        depends_on:
            - db

    frontend:
        build: ./frontend
        container_name: frontend-container
        image: frontend-app
        ports:
            - 3000:3000
        
volumes:
    mongo_db:
            